import { NodeData } from "@/lib/type";

export const defaultStatusConfig = {
  color: "text-emerald-400",
  bg: "bg-emerald-500/10",
  border: "border-emerald-500/30",
  ring: "#10b981",
  badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
  dot: "bg-emerald-400",
};

export const statusConfig = {
  Aman: {
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    ring: "#10b981",
    badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    dot: "bg-emerald-400",
  },
  Waspada: {
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    ring: "#f59e0b",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    dot: "bg-amber-400",
  },
  Kritis: {
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30",
    ring: "#f43f5e",
    badge: "bg-rose-500/20 text-rose-300 border-rose-500/40",
    dot: "bg-rose-400",
  },
  Penuh: {
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/30",
    ring: "#a855f7",
    badge: "bg-purple-500/20 text-purple-300 border-purple-500/40",
    dot: "bg-purple-400",
  },
};

export const INITIAL_NODES: NodeData[] = [
  {
    node_id: "ST-001",
    location: "Blok A - Unit 12",
    timestamp: new Date(),
    online: true,
    level_cm: 145,
    level_pct: 72,
    h2s_ppm: 3.2,
    ch4_ppm: 420,
    nh3_ppm: 8.1,
    temp_c: 31.2,
    humidity_pct: 78,
    ph: 7.45,
    turbidity_ntu: 45,
    status: "Waspada",
    alerts: [
      {
        id: "a1",
        severity: "warning",
        type: "Level Tinggi",
        message: "Level septic tank mendekati 75% kapasitas",
        value: 72,
        unit: "%",
        timestamp: new Date(Date.now() - 12 * 60000),
        acknowledged: false,
      },
    ],
  },
  {
    node_id: "ST-002",
    location: "Blok B - Unit 05",
    timestamp: new Date(Date.now() - 45000),
    online: true,
    level_cm: 89,
    level_pct: 44,
    h2s_ppm: 1.1,
    ch4_ppm: 210,
    nh3_ppm: 4.5,
    temp_c: 29.8,
    humidity_pct: 72,
    ph: 7.1,
    turbidity_ntu: 28,
    status: "Aman",
    alerts: [],
  },
  {
    node_id: "ST-003",
    location: "Blok C - Unit 21",
    timestamp: new Date(Date.now() - 3 * 60000),
    online: false,
    level_cm: 188,
    level_pct: 94,
    h2s_ppm: 12.8,
    ch4_ppm: 1250,
    nh3_ppm: 28.4,
    temp_c: 34.1,
    humidity_pct: 85,
    ph: 6.8,
    turbidity_ntu: 180,
    status: "Kritis",
    alerts: [
      {
        id: "a2",
        severity: "critical",
        type: "H2S Kritis",
        message: "Konsentrasi H2S melampaui 10 ppm (OSHA limit)",
        value: 12.8,
        unit: "ppm",
        timestamp: new Date(Date.now() - 8 * 60000),
        acknowledged: false,
      },
      {
        id: "a3",
        severity: "critical",
        type: "CH4 Kritis",
        message: "Konsentrasi Metana melampaui 1000 ppm",
        value: 1250,
        unit: "ppm",
        timestamp: new Date(Date.now() - 6 * 60000),
        acknowledged: false,
      },
    ],
  },
  {
    node_id: "ST-004",
    location: "Blok D - Unit 03",
    timestamp: new Date(Date.now() - 20000),
    online: true,
    level_cm: 201,
    level_pct: 100,
    h2s_ppm: 2.0,
    ch4_ppm: 380,
    nh3_ppm: 5.2,
    temp_c: 30.5,
    humidity_pct: 74,
    ph: 7.3,
    turbidity_ntu: 60,
    status: "Penuh",
    alerts: [
      {
        id: "a4",
        severity: "critical",
        type: "Tank Penuh",
        message:
          "Septic tank telah mencapai kapasitas maksimum — segera kuras!",
        value: 100,
        unit: "%",
        timestamp: new Date(Date.now() - 2 * 60000),
        acknowledged: false,
      },
    ],
  },
];
export const INITIAL_ONE_NODE: NodeData = {
  node_id: "ST-001",
  location: "Blok A - Unit 12",
  timestamp: new Date(),
  online: true,
  level_cm: 145,
  level_pct: 72,
  h2s_ppm: 3.2,
  ch4_ppm: 420,
  nh3_ppm: 8.1,
  temp_c: 31.2,
  humidity_pct: 78,
  ph: 7.45,
  turbidity_ntu: 45,
  status: "Waspada",
  alerts: [
    {
      id: "a1",
      severity: "warning",
      type: "Level Tinggi",
      message: "Level septic tank mendekati 75% kapasitas",
      value: 72,
      unit: "%",
      timestamp: new Date(Date.now() - 12 * 60000),
      acknowledged: false,
    },
  ],
};
